create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  action text not null,
  status text not null,
  details jsonb,
  ip_address text,
  user_agent text,
  created_at timestamptz default now() not null
);

create index if not exists idx_audit_user on public.audit_logs(user_id);
create index if not exists idx_audit_action on public.audit_logs(action);
create index if not exists idx_audit_created_at on public.audit_logs(created_at);
