-- ============================================================================
-- Calibration Order — 01 Schema
-- Tabel: calibration_orders, personnel, schedule_history, items,
--        counters, counter_logs
-- Idempotent: aman dijalankan berulang.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Counter nomor order (scope: tahun + FC/LC)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.calibration_order_counters (
  numbering_year      smallint    NOT NULL,
  calibration_place   varchar(2)  NOT NULL,
  last_value          integer     NOT NULL DEFAULT 0,
  updated_at          timestamptz NOT NULL DEFAULT now(),
  updated_by          uuid,
  CONSTRAINT calibration_order_counters_pkey
    PRIMARY KEY (numbering_year, calibration_place),
  CONSTRAINT calibration_order_counters_place_chk
    CHECK (calibration_place IN ('FC', 'LC')),
  CONSTRAINT calibration_order_counters_last_value_chk
    CHECK (last_value >= 0)
);

-- ---------------------------------------------------------------------------
-- Order kalibrasi
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.calibration_orders (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numbering_year            smallint,
  order_number              integer,
  no_order                  varchar(10),
  station_id                bigint      NOT NULL REFERENCES public.station(id),
  station_address_snapshot  text,
  planned_date              date        NOT NULL,
  planned_end_date          date,
  calibration_place         varchar(2)  NOT NULL,
  status                    varchar(20) NOT NULL DEFAULT 'draft',
  notes                     text,
  created_by                uuid        NOT NULL,
  confirmed_at              timestamptz,
  started_at                timestamptz,
  completed_at              timestamptz,
  postponed_at              timestamptz,
  cancelled_at              timestamptz,
  cancellation_reason       text,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT calibration_orders_place_chk
    CHECK (calibration_place IN ('FC', 'LC')),
  CONSTRAINT calibration_orders_status_chk
    CHECK (status IN ('draft','booked','postponed','in_progress','completed','cancelled')),
  CONSTRAINT calibration_orders_order_number_chk
    CHECK (order_number IS NULL OR order_number > 0),
  CONSTRAINT calibration_orders_planned_range_chk
    CHECK (planned_end_date IS NULL OR planned_end_date >= planned_date)
);

-- Upgrade schema lama: draft belum memiliki nomor sampai dikonfirmasi.
ALTER TABLE public.calibration_orders
  ALTER COLUMN numbering_year DROP NOT NULL,
  ALTER COLUMN order_number DROP NOT NULL,
  ALTER COLUMN no_order DROP NOT NULL;

ALTER TABLE public.calibration_orders
  ADD COLUMN IF NOT EXISTS planned_end_date date;

UPDATE public.calibration_orders
   SET planned_end_date = planned_date
 WHERE planned_end_date IS NULL;

ALTER TABLE public.calibration_orders
  ALTER COLUMN planned_end_date SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conname = 'calibration_orders_planned_range_chk'
  ) THEN
    ALTER TABLE public.calibration_orders
      ADD CONSTRAINT calibration_orders_planned_range_chk
      CHECK (planned_end_date >= planned_date);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS calibration_orders_no_order_uk
  ON public.calibration_orders (numbering_year, calibration_place, order_number);

-- FC dan LC memiliki counter terpisah; no_order "001" boleh muncul satu kali
-- pada masing-masing scope di tahun yang sama.
DROP INDEX IF EXISTS public.calibration_orders_no_order_text_uk;
CREATE UNIQUE INDEX IF NOT EXISTS calibration_orders_no_order_text_scope_uk
  ON public.calibration_orders (numbering_year, calibration_place, no_order);

CREATE INDEX IF NOT EXISTS calibration_orders_station_idx
  ON public.calibration_orders (station_id, status);

CREATE INDEX IF NOT EXISTS calibration_orders_status_idx
  ON public.calibration_orders (status);

-- ---------------------------------------------------------------------------
-- Petugas kalibrasi per order
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.calibration_order_personnel (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     bigint      NOT NULL REFERENCES public.calibration_orders(id) ON DELETE CASCADE,
  personel_id  uuid        NOT NULL,
  assigned_by  uuid,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT calibration_order_personnel_uk UNIQUE (order_id, personel_id)
);

-- ---------------------------------------------------------------------------
-- Histori jadwal (penundaan / perubahan tanggal)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.calibration_order_schedule_history (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id          bigint      NOT NULL REFERENCES public.calibration_orders(id) ON DELETE CASCADE,
  old_planned_date  date,
  new_planned_date  date,
  old_planned_end_date date,
  new_planned_end_date date,
  reason            text,
  changed_by        uuid,
  changed_at        timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.calibration_order_schedule_history
  ADD COLUMN IF NOT EXISTS old_planned_end_date date,
  ADD COLUMN IF NOT EXISTS new_planned_end_date date;

CREATE INDEX IF NOT EXISTS calibration_order_schedule_history_order_idx
  ON public.calibration_order_schedule_history (order_id);

-- ---------------------------------------------------------------------------
-- Item order = satu alat/sistem aktual (dibuat saat alat diketahui)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.calibration_order_items (
  id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id                 bigint      NOT NULL REFERENCES public.calibration_orders(id) ON DELETE CASCADE,
  identification_sequence  integer     NOT NULL,
  no_identification        varchar(20) NOT NULL,
  instrument_id            bigint      REFERENCES public.instrument(id),
  instrument_code          text,
  status                   varchar(20) NOT NULL DEFAULT 'identified',
  created_by               uuid,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  voided_at                timestamptz,
  void_reason              text,
  CONSTRAINT calibration_order_items_status_chk
    CHECK (status IN ('identified','certificate_draft','completed','void')),
  CONSTRAINT calibration_order_items_seq_chk
    CHECK (identification_sequence > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS calibration_order_items_order_seq_uk
  ON public.calibration_order_items (order_id, identification_sequence);

-- no_identification adalah nomor bisnis berscope order. Nilai teks seperti
-- "001.001" dapat muncul lagi pada tahun/place berbeda setelah reset tahunan;
-- keunikan otoritatif dijaga oleh (order_id, identification_sequence).
DROP INDEX IF EXISTS public.calibration_order_items_no_ident_uk;

CREATE INDEX IF NOT EXISTS calibration_order_items_order_idx
  ON public.calibration_order_items (order_id);

CREATE INDEX IF NOT EXISTS calibration_order_items_instrument_idx
  ON public.calibration_order_items (instrument_id);

-- ---------------------------------------------------------------------------
-- Log aksi counter (hard reset / repair / skip)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.calibration_order_counter_logs (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numbering_year  smallint   NOT NULL,
  calibration_place varchar(2) NOT NULL,
  previous_value  integer,
  new_value       integer,
  action          varchar(30) NOT NULL,
  reason          text,
  performed_by    uuid,
  performed_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS calibration_order_counter_logs_scope_idx
  ON public.calibration_order_counter_logs (numbering_year, calibration_place);

-- ---------------------------------------------------------------------------
-- Link certificate -> order & order item
-- ---------------------------------------------------------------------------
ALTER TABLE public.certificate
  ADD COLUMN IF NOT EXISTS calibration_order_id      bigint,
  ADD COLUMN IF NOT EXISTS calibration_order_item_id bigint;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'certificate_calibration_order_fk'
  ) THEN
    ALTER TABLE public.certificate
      ADD CONSTRAINT certificate_calibration_order_fk
      FOREIGN KEY (calibration_order_id)
      REFERENCES public.calibration_orders(id);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'certificate_calibration_order_item_fk'
  ) THEN
    ALTER TABLE public.certificate
      ADD CONSTRAINT certificate_calibration_order_item_fk
      FOREIGN KEY (calibration_order_item_id)
      REFERENCES public.calibration_order_items(id);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS certificate_one_per_order_item_uk
  ON public.certificate (calibration_order_item_id)
  WHERE calibration_order_item_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- updated_at trigger
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at_generic()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS calibration_orders_set_updated_at ON public.calibration_orders;
CREATE TRIGGER calibration_orders_set_updated_at
  BEFORE UPDATE ON public.calibration_orders
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_generic();

DROP TRIGGER IF EXISTS calibration_order_items_set_updated_at ON public.calibration_order_items;
CREATE TRIGGER calibration_order_items_set_updated_at
  BEFORE UPDATE ON public.calibration_order_items
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_generic();

-- ---------------------------------------------------------------------------
-- RLS: tabel baru hanya diakses via service role (API). Aktifkan RLS tanpa
-- policy anon/authenticated agar tidak terekspos ke browser.
-- ---------------------------------------------------------------------------
ALTER TABLE public.calibration_orders                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calibration_order_personnel        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calibration_order_schedule_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calibration_order_items            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calibration_order_counters         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calibration_order_counter_logs     ENABLE ROW LEVEL SECURITY;
