CREATE TABLE IF NOT EXISTS public.cmc_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(50) NOT NULL,
  name varchar(255) NOT NULL,
  parameter_code varchar(20) NOT NULL,
  calibration_method varchar(255),
  instrument_name_id bigint REFERENCES public.instrument_names(id) ON DELETE SET NULL,
  source_document varchar(255),
  version integer NOT NULL DEFAULT 1,
  effective_from date NOT NULL DEFAULT CURRENT_DATE,
  effective_until date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (code, version),
  CHECK (effective_until IS NULL OR effective_until >= effective_from)
);

CREATE TABLE IF NOT EXISTS public.cmc_values (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cmc_profile_id bigint NOT NULL REFERENCES public.cmc_profiles(id) ON DELETE CASCADE,
  range_min numeric,
  range_max numeric,
  cmc_value numeric NOT NULL CHECK (cmc_value >= 0),
  unit varchar(50) NOT NULL,
  formula text,
  sequence integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cmc_values_profile_sequence_key UNIQUE (cmc_profile_id, sequence),
  CHECK (range_min IS NULL OR range_max IS NULL OR range_min <= range_max)
);

CREATE INDEX IF NOT EXISTS idx_cmc_profiles_active_parameter
  ON public.cmc_profiles(parameter_code, is_active, effective_from);
CREATE INDEX IF NOT EXISTS idx_cmc_values_profile_range
  ON public.cmc_values(cmc_profile_id, range_min, range_max, sequence);

-- Seed master CMC dari sheet CMC workbook. Upsert aman dijalankan berulang.
INSERT INTO public.cmc_profiles
  (code, name, parameter_code, calibration_method, source_document, version, effective_from, is_active)
VALUES
  ('CMC-TT-DIGITAL', 'Termometer Digital', 'TT', 'MK 01 - Suhu', 'Workbook CMC BMKG 2026', 1, '2026-01-01', true),
  ('CMC-TT-UDARA', 'Termometer Udara', 'TT', 'MK 01 - Suhu', 'Workbook CMC BMKG 2026', 1, '2026-01-01', true),
  ('CMC-TT-ANALOG', 'Termometer Analog', 'TT', 'MK 01 - Suhu', 'Workbook CMC BMKG 2026', 1, '2026-01-01', true),
  ('CMC-TT-GELAS', 'Termometer Gelas', 'TT', 'MK 01 - Suhu', 'Workbook CMC BMKG 2026', 1, '2026-01-01', true),
  ('CMC-RH-DIGITAL', 'Hygrometer Digital', 'RH', 'MK 03 - Kelembapan Udara Relatif', 'Workbook CMC BMKG 2026', 1, '2026-01-01', true),
  ('CMC-PP-DIGITAL', 'Barometer Digital', 'PP', 'MK 02 - Tekanan Udara', 'Workbook CMC BMKG 2026', 1, '2026-01-01', true),
  ('CMC-WS', 'Kecepatan Angin', 'WS', 'MK 04 - Anemometer (Kecepatan Angin)', 'Workbook CMC BMKG 2026', 1, '2026-01-01', true),
  ('CMC-WD', 'Arah Angin', 'WD', 'MK 05 - Anemometer (Arah Angin)', 'Workbook CMC BMKG 2026', 1, '2026-01-01', true),
  ('CMC-RR-ANALOG', 'Penakar Hujan Analog', 'RR', 'MK 06 - Penakar Hujan', 'Workbook CMC BMKG 2026', 1, '2026-01-01', true),
  ('CMC-RR-DIGITAL', 'Penakar Hujan Digital', 'RR', 'MK 06 - Penakar Hujan', 'Workbook CMC BMKG 2026', 1, '2026-01-01', true),
  ('CMC-SR', 'Pyranometer', 'SR', '-', 'Workbook CMC BMKG 2026', 1, '2026-01-01', true),
  ('CMC-WL', 'Water Level', 'WL', '-', 'Workbook CMC BMKG 2026', 1, '2026-01-01', true)
ON CONFLICT (code, version) DO UPDATE SET
  name = EXCLUDED.name,
  parameter_code = EXCLUDED.parameter_code,
  calibration_method = EXCLUDED.calibration_method,
  source_document = EXCLUDED.source_document,
  is_active = EXCLUDED.is_active,
  updated_at = now();

INSERT INTO public.cmc_values (cmc_profile_id, range_min, range_max, cmc_value, unit, sequence)
SELECT p.id, seed.range_min, seed.range_max, seed.cmc_value, seed.unit, 1
FROM (VALUES
  ('CMC-TT-DIGITAL', 0::numeric, 50::numeric, 0.01::numeric, '°C'),
  ('CMC-TT-UDARA', 0, 50, 0.3, '°C'),
  ('CMC-TT-ANALOG', 0, 50, 0.071, '°C'),
  ('CMC-TT-GELAS', 0, 50, 0.071, '°C'),
  ('CMC-RH-DIGITAL', 15, 95, 1.1, '%RH'),
  ('CMC-PP-DIGITAL', 700, 1100, 0.026, 'hPa'),
  ('CMC-WS', 0.4, 25, 0.48, 'm/s'),
  ('CMC-WD', 0, 360, 1, '°'),
  ('CMC-RR-ANALOG', 0, 25, 0.29, 'mm'),
  ('CMC-RR-DIGITAL', 0, 2.5, 0.19, 'mm')
) AS seed(code, range_min, range_max, cmc_value, unit)
JOIN public.cmc_profiles p ON p.code = seed.code AND p.version = 1
ON CONFLICT (cmc_profile_id, sequence) DO UPDATE SET
  range_min = EXCLUDED.range_min,
  range_max = EXCLUDED.range_max,
  cmc_value = EXCLUDED.cmc_value,
  unit = EXCLUDED.unit;
