-- Create calibration_sessions table
CREATE TABLE IF NOT EXISTS public.calibration_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    station_id BIGINT,
    start_date DATE,
    end_date DATE,
    place TEXT,
    notes TEXT,
    status TEXT DEFAULT 'draft',
    users UUID[] DEFAULT '{}'::UUID[]
);

-- Enable RLS for calibration_sessions
ALTER TABLE public.calibration_sessions ENABLE ROW LEVEL SECURITY;

-- Policy for calibration_sessions (allow all for now for ease, or specific rules)
CREATE POLICY "Enable all access for authenticated users" ON public.calibration_sessions
    FOR ALL USING (auth.role() = 'authenticated');

-- Create raw_data table
CREATE TABLE IF NOT EXISTS public.raw_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    session_id UUID REFERENCES public.calibration_sessions(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ,
    standard_data DOUBLE PRECISION,
    uut_data DOUBLE PRECISION,
    filename TEXT,
    uploaded_by UUID
);

-- Enable RLS for raw_data
ALTER TABLE public.raw_data ENABLE ROW LEVEL SECURITY;

-- Policy for raw_data
CREATE POLICY "Enable all access for authenticated users" ON public.raw_data
    FOR ALL USING (auth.role() = 'authenticated');

-- Grant access
GRANT ALL ON TABLE public.calibration_sessions TO authenticated;
GRANT ALL ON TABLE public.calibration_sessions TO service_role;
GRANT ALL ON TABLE public.raw_data TO authenticated;
GRANT ALL ON TABLE public.raw_data TO service_role;
