CREATE TABLE IF NOT EXISTS public.calibration_method_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(80) NOT NULL,
  name varchar(255) NOT NULL,
  instrument_scope varchar(30) NOT NULL,
  adapter_id varchar(80) NOT NULL,
  version integer NOT NULL DEFAULT 1,
  source_documents jsonb NOT NULL DEFAULT '[]'::jsonb,
  rules jsonb NOT NULL DEFAULT '{}'::jsonb,
  effective_from date NOT NULL DEFAULT CURRENT_DATE,
  effective_until date,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (code, version),
  CHECK (instrument_scope IN ('pyranometer', 'raw_general', 'tipping_bucket')),
  CHECK (effective_until IS NULL OR effective_until >= effective_from)
);

ALTER TABLE public.calibration_method_profiles
  ADD COLUMN IF NOT EXISTS adapter_id varchar(80);

UPDATE public.calibration_method_profiles
SET adapter_id = CASE instrument_scope
  WHEN 'pyranometer' THEN 'pyranometer-v1'
  WHEN 'raw_general' THEN 'raw-general-v1'
  WHEN 'tipping_bucket' THEN 'tipping-bucket-v1'
END
WHERE adapter_id IS NULL;

ALTER TABLE public.calibration_method_profiles
  ALTER COLUMN adapter_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_calibration_method_profiles_scope_active
  ON public.calibration_method_profiles(instrument_scope, is_active, effective_from);

INSERT INTO public.calibration_method_profiles
  (code, name, instrument_scope, adapter_id, version, source_documents, rules, effective_from, is_active, notes)
VALUES
  (
    'PYR-LEGACY-BMKG',
    'Pyranometer Legacy BMKG',
    'pyranometer',
    'pyranometer-v1',
    1,
    '[{"code":"ISO 9060","edition":"2018"},{"code":"ISO 9847","edition":"1992"},{"code":"WMO-No. 8","edition":"2018"}]'::jsonb,
    '{"cfRule":"MEAN_ALL_VALID","outlierRule":"REPORT_ONLY","driftRule":"ISO_CLASSIFICATION","coverageRule":"STUDENT_T_95","resolutionRule":"RESOLUTION_OVER_MEAN"}'::jsonb,
    '2026-01-01', true,
    'Profil legacy awal. Perubahan formula wajib dibuat sebagai versi baru.'
  ),
  (
    'RAW-QC-GENERAL',
    'Raw Data QC General',
    'raw_general',
    'raw-general-v1',
    1,
    '[]'::jsonb,
    '{"calculationRule":"STD_CORRECTED_IN_UUT_UNIT_MINUS_UUT","uncertaintyRule":"GENERAL_FIVE_COMPONENT_BUDGET"}'::jsonb,
    '2026-01-01', true,
    'Profil umum untuk instrumen AWOS/AWS berbasis raw data.'
  ),
  (
    'RR-LEGACY-V1',
    'Tipping Bucket Legacy Workbook',
    'tipping_bucket',
    'tipping-bucket-v1',
    1,
    '[{"code":"WMO-No. 8","edition":"2018"},{"code":"MK 06","edition":"current"}]'::jsonb,
    '{"calculationRule":"standardRainfall=resolutionUut*testVolume/volumePerTip; correction=standardRainfall-UUT","repeatabilityDivisor":"sqrt(5)","diameterDivisor":"sqrt(5)","coverageRule":"STUDENT_T_95"}'::jsonb,
    '2026-01-01', true,
    'Profil legacy untuk kompatibilitas workbook Tipping Bucket.'
  )
ON CONFLICT (code, version) DO NOTHING;
