-- ============================================================================
-- SURAT KETERANGAN (Letter) — skema + master item pemeriksaan
-- ----------------------------------------------------------------------------
-- Keputusan: Surat Keterangan disimpan di tabel `letter` SENDIRI (data terpisah
-- dari sertifikat), tetapi DI-LINK ke `certificate` + order item agar data
-- order/identifikasi/instrumen/pemilik/verifikator dapat dikumpulkan dari sana.
--
-- Isi pemeriksaan (PARAMETER -> HASIL) berasal dari master `inspection_items`
-- (per jenis alat); hasil per surat disimpan di `letter_inspection_results`.
--
-- Idempoten. Tidak menyentuh tipping bucket / pyranometer / raw_general.
-- ============================================================================

BEGIN;

-- 1) Master item pemeriksaan (per jenis alat) -------------------------------
CREATE TABLE IF NOT EXISTS public.inspection_items (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instrument_name_id bigint REFERENCES public.instrument_names(id) ON DELETE CASCADE,
  section            varchar(120),
  parameter          varchar(255) NOT NULL,
  sort_order         integer NOT NULL DEFAULT 0,
  is_active          boolean NOT NULL DEFAULT true,
  created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS inspection_items_name_idx
  ON public.inspection_items (instrument_name_id, sort_order);

-- 2) Perluas `letter`: link + header surat keterangan -----------------------
ALTER TABLE public.letter
  ADD COLUMN IF NOT EXISTS certificate_id             bigint REFERENCES public.certificate(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS calibration_order_id       bigint REFERENCES public.calibration_orders(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS calibration_order_item_id  bigint REFERENCES public.calibration_order_items(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS sensor                     bigint REFERENCES public.sensor(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS no_order                   varchar(10),
  ADD COLUMN IF NOT EXISTS no_identification          varchar(20),
  ADD COLUMN IF NOT EXISTS inspection_date            date,
  ADD COLUMN IF NOT EXISTS inspection_place           text,
  ADD COLUMN IF NOT EXISTS reference_document         text,
  ADD COLUMN IF NOT EXISTS notes                      text,
  ADD COLUMN IF NOT EXISTS verifikator_1              uuid,
  ADD COLUMN IF NOT EXISTS verifikator_2              uuid,
  ADD COLUMN IF NOT EXISTS verifikator_3              uuid,
  ADD COLUMN IF NOT EXISTS status                     varchar(20) NOT NULL DEFAULT 'draft',
  ADD COLUMN IF NOT EXISTS created_by                 uuid;

-- Satu surat keterangan per order item (bila item ditentukan).
CREATE UNIQUE INDEX IF NOT EXISTS letter_one_per_order_item_uk
  ON public.letter (calibration_order_item_id)
  WHERE calibration_order_item_id IS NOT NULL;

-- Longgarkan NOT NULL: surat boleh dibuat sebelum nomor/tanggal terbit tersedia.
ALTER TABLE public.letter ALTER COLUMN issue_date DROP NOT NULL;
ALTER TABLE public.letter ALTER COLUMN no_letter DROP NOT NULL;

-- 3) Hasil pemeriksaan per surat -------------------------------------------
CREATE TABLE IF NOT EXISTS public.letter_inspection_results (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  letter_id          bigint NOT NULL REFERENCES public.letter(id) ON DELETE CASCADE,
  inspection_item_id bigint REFERENCES public.inspection_items(id) ON DELETE SET NULL,
  parameter          varchar(255) NOT NULL,
  hasil              text,
  sort_order         integer NOT NULL DEFAULT 0,
  created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS letter_inspection_results_letter_idx
  ON public.letter_inspection_results (letter_id, sort_order);

-- 4) RLS: akses hanya via service role (API) --------------------------------
ALTER TABLE public.inspection_items            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.letter_inspection_results   ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verifikasi:
--   SELECT column_name FROM information_schema.columns WHERE table_name='letter' AND column_name='certificate_id';
--   SELECT to_regclass('public.inspection_items'), to_regclass('public.letter_inspection_results');
