BEGIN;

CREATE TABLE IF NOT EXISTS public.order_item_document_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calibration_order_item_id bigint NOT NULL UNIQUE
    REFERENCES public.calibration_order_items(id) ON DELETE CASCADE,
  verifikator_1 uuid REFERENCES public.personel(id),
  verifikator_2 uuid REFERENCES public.personel(id),
  verifikator_3 uuid REFERENCES public.personel(id),
  authorized_by uuid REFERENCES public.personel(id),
  revision integer NOT NULL DEFAULT 1 CHECK (revision > 0),
  locked_at timestamptz,
  locked_by uuid REFERENCES public.personel(id),
  created_by uuid REFERENCES public.personel(id),
  updated_by uuid REFERENCES public.personel(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT order_item_document_assignment_distinct_chk CHECK (
    verifikator_1 IS NULL OR verifikator_2 IS NULL OR verifikator_3 IS NULL OR authorized_by IS NULL
    OR (
      verifikator_1 <> verifikator_2 AND verifikator_1 <> verifikator_3
      AND verifikator_1 <> authorized_by AND verifikator_2 <> verifikator_3
      AND verifikator_2 <> authorized_by AND verifikator_3 <> authorized_by
    )
  )
);

CREATE TABLE IF NOT EXISTS public.order_item_document_checkers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id bigint NOT NULL REFERENCES public.order_item_document_assignments(id) ON DELETE CASCADE,
  personel_id uuid NOT NULL REFERENCES public.personel(id),
  sort_order integer NOT NULL CHECK (sort_order >= 0),
  assigned_by uuid REFERENCES public.personel(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (assignment_id, personel_id),
  UNIQUE (assignment_id, sort_order)
);

CREATE TABLE IF NOT EXISTS public.order_item_document_assignment_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id bigint NOT NULL REFERENCES public.order_item_document_assignments(id) ON DELETE RESTRICT,
  revision integer NOT NULL,
  checked_by jsonb NOT NULL,
  verifikator_1 jsonb NOT NULL,
  verifikator_2 jsonb NOT NULL,
  verifikator_3 jsonb NOT NULL,
  authorized_by jsonb NOT NULL,
  lock_source varchar(40) NOT NULL,
  locked_at timestamptz NOT NULL,
  locked_by uuid NOT NULL REFERENCES public.personel(id),
  reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (assignment_id, revision)
);

CREATE TABLE IF NOT EXISTS public.order_item_document_assignment_conflicts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calibration_order_item_id bigint NOT NULL REFERENCES public.calibration_order_items(id) ON DELETE CASCADE,
  certificate_assignment jsonb,
  letter_assignment jsonb,
  resolved_at timestamptz,
  resolved_by uuid REFERENCES public.personel(id),
  resolution_notes text,
  detected_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (calibration_order_item_id)
);

CREATE TABLE IF NOT EXISTS public.order_item_document_assignment_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id bigint NOT NULL REFERENCES public.order_item_document_assignments(id) ON DELETE CASCADE,
  action varchar(40) NOT NULL,
  revision integer NOT NULL,
  reason text,
  performed_by uuid REFERENCES public.personel(id),
  performed_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public._document_person_snapshot(p_id uuid)
RETURNS jsonb
LANGUAGE sql
STABLE
SET search_path TO 'public'
AS $fn$
  SELECT jsonb_build_object(
    'id', p.id,
    'name', p.name,
    'nip', p.nip,
    'position', p.position,
    'signer_title', p.signer_title,
    'balai_id', p.balai_id
  )
  FROM public.personel p
  WHERE p.id = p_id AND p.is_active = true AND p.deleted_at IS NULL;
$fn$;

CREATE OR REPLACE FUNCTION public._validate_document_assignment_person(
  p_id uuid,
  p_role text,
  p_label text
)
RETURNS void
LANGUAGE plpgsql
STABLE
SET search_path TO 'public'
AS $fn$
DECLARE
  v_active boolean;
  v_role text;
BEGIN
  SELECT p.is_active AND p.deleted_at IS NULL, ur.role
  INTO v_active, v_role
  FROM public.personel p
  LEFT JOIN public.user_roles ur ON ur.user_id = p.id
  WHERE p.id = p_id;

  IF NOT FOUND OR NOT COALESCE(v_active, false) THEN
    RAISE EXCEPTION '% harus merupakan personel aktif', p_label;
  END IF;
  IF p_role = 'verifikator' AND v_role <> 'verifikator' THEN
    RAISE EXCEPTION '% harus memiliki role verifikator', p_label;
  END IF;
  IF p_role = 'signer' AND v_role <> 'assignor' THEN
    RAISE EXCEPTION '% harus memiliki role assignor', p_label;
  END IF;
END;
$fn$;

CREATE OR REPLACE FUNCTION public.save_order_item_document_assignment(p_data jsonb)
RETURNS SETOF public.order_item_document_assignments
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $fn$
DECLARE
  v_item_id bigint := NULLIF(p_data->>'calibration_order_item_id', '')::bigint;
  v_actor uuid := NULLIF(p_data->>'actor_id', '')::uuid;
  v_v1 uuid := NULLIF(p_data->>'verifikator_1', '')::uuid;
  v_v2 uuid := NULLIF(p_data->>'verifikator_2', '')::uuid;
  v_v3 uuid := NULLIF(p_data->>'verifikator_3', '')::uuid;
  v_signer uuid := NULLIF(p_data->>'authorized_by', '')::uuid;
  v_assignment public.order_item_document_assignments%ROWTYPE;
  v_order_id bigint;
  v_item_status text;
  v_actor_role text;
  v_checker jsonb;
  v_checker_id uuid;
  v_sort integer := 0;
BEGIN
  IF v_item_id IS NULL OR v_actor IS NULL THEN RAISE EXCEPTION 'Order item dan actor wajib diisi'; END IF;
  IF v_v1 IS NULL OR v_v2 IS NULL OR v_v3 IS NULL OR v_signer IS NULL THEN
    RAISE EXCEPTION 'Verifikator 1, 2, 3, dan penandatangan wajib diisi';
  END IF;
  IF jsonb_array_length(COALESCE(p_data->'checked_by_ids', '[]'::jsonb)) = 0 THEN
    RAISE EXCEPTION 'Minimal satu pemeriksa wajib dipilih';
  END IF;

  SELECT i.order_id, i.status INTO v_order_id, v_item_status
  FROM public.calibration_order_items i WHERE i.id = v_item_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Order item tidak ditemukan'; END IF;
  IF v_item_status = 'void' THEN RAISE EXCEPTION 'Order item sudah tidak dipakai'; END IF;

  SELECT role INTO v_actor_role FROM public.user_roles WHERE user_id = v_actor;
  IF v_actor_role <> 'admin' AND NOT EXISTS (
    SELECT 1 FROM public.calibration_orders o
    WHERE o.id = v_order_id AND o.created_by = v_actor
    UNION ALL
    SELECT 1 FROM public.calibration_order_personnel cop
    WHERE cop.order_id = v_order_id AND cop.personel_id = v_actor
  ) THEN
    RAISE EXCEPTION 'Actor bukan anggota tim order';
  END IF;
  IF v_actor_role NOT IN ('admin', 'calibrator') THEN
    RAISE EXCEPTION 'Hanya admin atau Petugas Kalibrasi yang dapat mengatur penugasan';
  END IF;

  PERFORM public._validate_document_assignment_person(v_v1, 'verifikator', 'Verifikator 1');
  PERFORM public._validate_document_assignment_person(v_v2, 'verifikator', 'Verifikator 2');
  PERFORM public._validate_document_assignment_person(v_v3, 'verifikator', 'Verifikator 3');
  PERFORM public._validate_document_assignment_person(v_signer, 'signer', 'Penandatangan');

  INSERT INTO public.order_item_document_assignments (
    calibration_order_item_id, verifikator_1, verifikator_2, verifikator_3,
    authorized_by, created_by, updated_by
  ) VALUES (v_item_id, v_v1, v_v2, v_v3, v_signer, v_actor, v_actor)
  ON CONFLICT (calibration_order_item_id) DO UPDATE SET
    verifikator_1 = EXCLUDED.verifikator_1,
    verifikator_2 = EXCLUDED.verifikator_2,
    verifikator_3 = EXCLUDED.verifikator_3,
    authorized_by = EXCLUDED.authorized_by,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
  WHERE order_item_document_assignments.locked_at IS NULL
  RETURNING * INTO v_assignment;

  IF v_assignment.id IS NULL THEN RAISE EXCEPTION 'Penugasan sudah dikunci dan tidak dapat diubah'; END IF;

  DELETE FROM public.order_item_document_checkers WHERE assignment_id = v_assignment.id;
  FOR v_checker IN SELECT value FROM jsonb_array_elements(p_data->'checked_by_ids') LOOP
    v_checker_id := trim(both '"' from v_checker::text)::uuid;
    IF NOT EXISTS (
      SELECT 1 FROM public.personel p
      WHERE p.id = v_checker_id AND p.is_active = true AND p.deleted_at IS NULL
    ) THEN RAISE EXCEPTION 'Pemeriksa % bukan personel aktif', v_checker_id; END IF;
    IF NOT EXISTS (
      SELECT 1 FROM public.calibration_orders o
      WHERE o.id = v_order_id AND o.created_by = v_checker_id
      UNION ALL
      SELECT 1 FROM public.calibration_order_personnel cop
      WHERE cop.order_id = v_order_id AND cop.personel_id = v_checker_id
    ) THEN RAISE EXCEPTION 'Pemeriksa harus anggota Tim Order'; END IF;
    INSERT INTO public.order_item_document_checkers (assignment_id, personel_id, sort_order, assigned_by)
    VALUES (v_assignment.id, v_checker_id, v_sort, v_actor);
    v_sort := v_sort + 1;
  END LOOP;

  UPDATE public.certificate SET
    verifikator_1 = v_v1, verifikator_2 = v_v2, verifikator_3 = v_v3,
    authorized_by = v_signer, assignor = v_signer
  WHERE calibration_order_item_id = v_item_id AND status = 'draft';
  UPDATE public.letter SET
    verifikator_1 = v_v1, verifikator_2 = v_v2, verifikator_3 = v_v3,
    authorized_by = v_signer
  WHERE calibration_order_item_id = v_item_id AND status = 'draft';

  INSERT INTO public.order_item_document_assignment_audit (assignment_id, action, revision, performed_by)
  VALUES (v_assignment.id, 'saved', v_assignment.revision, v_actor);

  RETURN QUERY SELECT * FROM public.order_item_document_assignments WHERE id = v_assignment.id;
END;
$fn$;

CREATE OR REPLACE FUNCTION public.lock_order_item_document_assignment(
  p_item_id bigint,
  p_actor uuid,
  p_source text
)
RETURNS SETOF public.order_item_document_assignment_snapshots
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $fn$
DECLARE
  v_assignment public.order_item_document_assignments%ROWTYPE;
  v_snapshot public.order_item_document_assignment_snapshots%ROWTYPE;
  v_checked jsonb;
BEGIN
  SELECT * INTO v_assignment FROM public.order_item_document_assignments
  WHERE calibration_order_item_id = p_item_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Penugasan Dokumen belum diisi'; END IF;

  SELECT * INTO v_snapshot FROM public.order_item_document_assignment_snapshots
  WHERE assignment_id = v_assignment.id AND revision = v_assignment.revision;
  IF FOUND THEN RETURN NEXT v_snapshot; RETURN; END IF;

  IF v_assignment.verifikator_1 IS NULL OR v_assignment.verifikator_2 IS NULL
     OR v_assignment.verifikator_3 IS NULL OR v_assignment.authorized_by IS NULL THEN
    RAISE EXCEPTION 'Penugasan verifikator dan penandatangan belum lengkap';
  END IF;

  SELECT jsonb_agg(public._document_person_snapshot(c.personel_id) ORDER BY c.sort_order)
  INTO v_checked FROM public.order_item_document_checkers c WHERE c.assignment_id = v_assignment.id;
  IF v_checked IS NULL OR jsonb_array_length(v_checked) = 0 THEN RAISE EXCEPTION 'Pemeriksa belum dipilih'; END IF;

  INSERT INTO public.order_item_document_assignment_snapshots (
    assignment_id, revision, checked_by, verifikator_1, verifikator_2,
    verifikator_3, authorized_by, lock_source, locked_at, locked_by
  ) VALUES (
    v_assignment.id, v_assignment.revision, v_checked,
    public._document_person_snapshot(v_assignment.verifikator_1),
    public._document_person_snapshot(v_assignment.verifikator_2),
    public._document_person_snapshot(v_assignment.verifikator_3),
    public._document_person_snapshot(v_assignment.authorized_by),
    p_source, now(), p_actor
  ) RETURNING * INTO v_snapshot;

  UPDATE public.order_item_document_assignments SET
    locked_at = v_snapshot.locked_at, locked_by = p_actor, updated_at = now()
  WHERE id = v_assignment.id;

  UPDATE public.certificate SET
    verifikator_1 = v_assignment.verifikator_1,
    verifikator_2 = v_assignment.verifikator_2,
    verifikator_3 = v_assignment.verifikator_3,
    authorized_by = v_assignment.authorized_by,
    assignor = v_assignment.authorized_by
  WHERE calibration_order_item_id = p_item_id;
  UPDATE public.letter SET
    verifikator_1 = v_assignment.verifikator_1,
    verifikator_2 = v_assignment.verifikator_2,
    verifikator_3 = v_assignment.verifikator_3,
    authorized_by = v_assignment.authorized_by
  WHERE calibration_order_item_id = p_item_id;

  INSERT INTO public.order_item_document_assignment_audit (assignment_id, action, revision, performed_by)
  VALUES (v_assignment.id, 'locked:' || p_source, v_assignment.revision, p_actor);
  RETURN NEXT v_snapshot;
END;
$fn$;

CREATE OR REPLACE FUNCTION public.sync_document_assignment_to_new_document()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $fn$
DECLARE v_assignment public.order_item_document_assignments%ROWTYPE;
BEGIN
  IF NEW.calibration_order_item_id IS NULL THEN RETURN NEW; END IF;
  SELECT * INTO v_assignment FROM public.order_item_document_assignments
  WHERE calibration_order_item_id = NEW.calibration_order_item_id;
  IF NOT FOUND THEN RETURN NEW; END IF;
  IF TG_TABLE_NAME = 'certificate' THEN
    UPDATE public.certificate SET
      verifikator_1=v_assignment.verifikator_1,
      verifikator_2=v_assignment.verifikator_2,
      verifikator_3=v_assignment.verifikator_3,
      authorized_by=v_assignment.authorized_by,
      assignor=v_assignment.authorized_by
    WHERE id=NEW.id;
  ELSE
    UPDATE public.letter SET
      verifikator_1=v_assignment.verifikator_1,
      verifikator_2=v_assignment.verifikator_2,
      verifikator_3=v_assignment.verifikator_3,
      authorized_by=v_assignment.authorized_by
    WHERE id=NEW.id;
  END IF;
  RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS certificate_sync_document_assignment ON public.certificate;
CREATE TRIGGER certificate_sync_document_assignment
AFTER INSERT ON public.certificate FOR EACH ROW
EXECUTE FUNCTION public.sync_document_assignment_to_new_document();
DROP TRIGGER IF EXISTS letter_sync_document_assignment ON public.letter;
CREATE TRIGGER letter_sync_document_assignment
AFTER INSERT ON public.letter FOR EACH ROW
EXECUTE FUNCTION public.sync_document_assignment_to_new_document();

CREATE OR REPLACE FUNCTION public.protect_locked_document_assignment()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $fn$
BEGIN
  IF TG_OP = 'DELETE' AND OLD.locked_at IS NOT NULL THEN RAISE EXCEPTION 'Penugasan sudah dikunci'; END IF;
  IF TG_OP = 'UPDATE' AND OLD.locked_at IS NOT NULL AND (
    OLD.calibration_order_item_id IS DISTINCT FROM NEW.calibration_order_item_id
    OR OLD.verifikator_1 IS DISTINCT FROM NEW.verifikator_1
    OR OLD.verifikator_2 IS DISTINCT FROM NEW.verifikator_2
    OR OLD.verifikator_3 IS DISTINCT FROM NEW.verifikator_3
    OR OLD.authorized_by IS DISTINCT FROM NEW.authorized_by
  ) THEN RAISE EXCEPTION 'Penugasan sudah dikunci'; END IF;
  RETURN COALESCE(NEW, OLD);
END;
$fn$;

DROP TRIGGER IF EXISTS document_assignment_protect_locked ON public.order_item_document_assignments;
CREATE TRIGGER document_assignment_protect_locked
BEFORE UPDATE OR DELETE ON public.order_item_document_assignments
FOR EACH ROW EXECUTE FUNCTION public.protect_locked_document_assignment();

CREATE OR REPLACE FUNCTION public.protect_locked_document_checker()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public' AS $fn$
DECLARE v_assignment_id bigint := COALESCE(NEW.assignment_id, OLD.assignment_id);
BEGIN
  IF EXISTS (SELECT 1 FROM public.order_item_document_assignments WHERE id=v_assignment_id AND locked_at IS NOT NULL) THEN
    RAISE EXCEPTION 'Penugasan sudah dikunci';
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$fn$;

DROP TRIGGER IF EXISTS document_checker_protect_locked ON public.order_item_document_checkers;
CREATE TRIGGER document_checker_protect_locked
BEFORE INSERT OR UPDATE OR DELETE ON public.order_item_document_checkers
FOR EACH ROW EXECUTE FUNCTION public.protect_locked_document_checker();

CREATE OR REPLACE FUNCTION public.protect_document_assignment_snapshot()
RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN RAISE EXCEPTION 'Snapshot Penugasan Dokumen tidak dapat diubah'; END;
$fn$;
DROP TRIGGER IF EXISTS document_assignment_snapshot_immutable ON public.order_item_document_assignment_snapshots;
CREATE TRIGGER document_assignment_snapshot_immutable
BEFORE UPDATE OR DELETE ON public.order_item_document_assignment_snapshots
FOR EACH ROW EXECUTE FUNCTION public.protect_document_assignment_snapshot();

-- Backfill assignment dari Sertifikat terlebih dahulu, Surat sebagai fallback.
INSERT INTO public.order_item_document_assignment_conflicts (
  calibration_order_item_id, certificate_assignment, letter_assignment
)
SELECT c.calibration_order_item_id,
  jsonb_build_object('verifikator_1',c.verifikator_1,'verifikator_2',c.verifikator_2,'verifikator_3',c.verifikator_3,'authorized_by',c.authorized_by),
  jsonb_build_object('verifikator_1',l.verifikator_1,'verifikator_2',l.verifikator_2,'verifikator_3',l.verifikator_3,'authorized_by',l.authorized_by)
FROM public.certificate c JOIN public.letter l USING (calibration_order_item_id)
WHERE ROW(c.verifikator_1,c.verifikator_2,c.verifikator_3,c.authorized_by)
  IS DISTINCT FROM ROW(l.verifikator_1,l.verifikator_2,l.verifikator_3,l.authorized_by)
ON CONFLICT (calibration_order_item_id) DO NOTHING;

INSERT INTO public.order_item_document_assignments (
  calibration_order_item_id, verifikator_1, verifikator_2, verifikator_3, authorized_by
)
SELECT i.id,
  COALESCE(c.verifikator_1, l.verifikator_1),
  COALESCE(c.verifikator_2, l.verifikator_2),
  COALESCE(c.verifikator_3, l.verifikator_3),
  COALESCE(c.authorized_by, l.authorized_by)
FROM public.calibration_order_items i
LEFT JOIN public.certificate c ON c.calibration_order_item_id = i.id
LEFT JOIN public.letter l ON l.calibration_order_item_id = i.id
WHERE c.id IS NOT NULL OR l.id IS NOT NULL
ON CONFLICT (calibration_order_item_id) DO NOTHING;

INSERT INTO public.order_item_document_checkers (assignment_id, personel_id, sort_order)
SELECT a.id, team.personel_id, row_number() OVER (PARTITION BY a.id ORDER BY team.priority, team.personel_id) - 1
FROM public.order_item_document_assignments a
JOIN public.calibration_order_items i ON i.id = a.calibration_order_item_id
JOIN LATERAL (
  SELECT o.created_by AS personel_id, 0 AS priority FROM public.calibration_orders o
  WHERE o.id = i.order_id AND o.created_by IS NOT NULL
  UNION
  SELECT cop.personel_id, 1 FROM public.calibration_order_personnel cop WHERE cop.order_id = i.order_id
) team ON true
WHERE NOT EXISTS (SELECT 1 FROM public.order_item_document_checkers c WHERE c.assignment_id = a.id)
ON CONFLICT DO NOTHING;

ALTER TABLE public.order_item_document_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_item_document_checkers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_item_document_assignment_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_item_document_assignment_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_item_document_assignment_conflicts ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON FUNCTION public.save_order_item_document_assignment(jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.lock_order_item_document_assignment(bigint, uuid, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.save_order_item_document_assignment(jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.lock_order_item_document_assignment(bigint, uuid, text) TO service_role;

COMMIT;
