-- ============================================================================
-- STAGING ONLY: lengkapi 11 tabel yang ada di production tetapi belum ada di
-- project staging Supabase Cloud, supaya `security_migration_01/02` dapat diuji
-- end-to-end. Idempotent (aman dijalankan berulang).
--
-- JANGAN dijalankan di production: di production tabel-tabel ini sudah ada.
-- ============================================================================

-- ─── Sequences ───────────────────────────────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS public.calibration_measurement_measurement_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.logger_discovery_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.logger_rows_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.qc_uncertainty_components_id_seq;

-- ─── calibration_import ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.calibration_import (
  import_id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  source text NOT NULL,
  file_name text,
  imported_at timestamp with time zone NOT NULL DEFAULT now(),
  notes jsonb,
  PRIMARY KEY (import_id)
);

CREATE TABLE IF NOT EXISTS public.calibration_import_sheet (
  sheet_id uuid NOT NULL DEFAULT gen_random_uuid(),
  import_id uuid NOT NULL,
  sheet_name text NOT NULL,
  ts_column text,
  sheet_kind text,
  notes jsonb,
  PRIMARY KEY (sheet_id)
);

CREATE TABLE IF NOT EXISTS public.calibration_import_mapping (
  mapping_id uuid NOT NULL DEFAULT gen_random_uuid(),
  sheet_id uuid NOT NULL,
  raw_column_name text NOT NULL,
  parameter_code text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  unit text,
  avg_window_sec integer,
  transform jsonb,
  priority integer DEFAULT 0,
  PRIMARY KEY (mapping_id)
);

CREATE TABLE IF NOT EXISTS public.calibration_measurement (
  measurement_id bigint NOT NULL DEFAULT nextval('public.calibration_measurement_measurement_id_seq'::regclass),
  session_id uuid NOT NULL,
  import_id uuid,
  sheet_id uuid,
  source text NOT NULL,
  ts timestamp with time zone NOT NULL,
  parameter_code text NOT NULL,
  value numeric,
  unit text,
  avg_window_sec integer,
  raw_column_name text,
  row_no integer,
  quality jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (measurement_id)
);

-- ─── Master CMC ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.cmc_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(50) NOT NULL,
  name varchar(255) NOT NULL,
  parameter_code varchar(20) NOT NULL,
  calibration_method varchar(255),
  instrument_name_id bigint,
  source_document varchar(255),
  version integer NOT NULL DEFAULT 1,
  effective_from date NOT NULL DEFAULT CURRENT_DATE,
  effective_until date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cmc_profiles_code_version_key UNIQUE (code, version)
);

CREATE TABLE IF NOT EXISTS public.cmc_values (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cmc_profile_id bigint NOT NULL REFERENCES public.cmc_profiles(id) ON DELETE CASCADE,
  range_min numeric,
  range_max numeric,
  cmc_value numeric NOT NULL CHECK (cmc_value >= 0),
  unit varchar(50) NOT NULL,
  formula text,
  sequence integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cmc_values_profile_sequence_key UNIQUE (cmc_profile_id, sequence)
);

-- ─── Logger ingest ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.logger_discovery (
  id bigint NOT NULL DEFAULT nextval('public.logger_discovery_id_seq'::regclass),
  run_id uuid NOT NULL,
  logger_station_code text,
  value_index integer,
  is_numeric_ratio numeric,
  sample_min numeric,
  sample_max numeric,
  sample_mean numeric,
  sample_stddev numeric,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.logger_rows (
  id bigint NOT NULL DEFAULT nextval('public.logger_rows_id_seq'::regclass),
  run_id uuid NOT NULL,
  row_no integer NOT NULL,
  logger_station_code text,
  ts timestamp with time zone,
  "values" jsonb,
  raw_line text,
  parse_ok boolean DEFAULT false,
  parse_error text,
  PRIMARY KEY (id)
);

-- ─── QC pipeline ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.qc_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  certificate_id bigint,
  station_id bigint,
  instrument_id bigint,
  sensor_id bigint,
  status text DEFAULT 'uploaded'::text,
  qc_version text DEFAULT 'v1'::text,
  logger_file_path text,
  std_certificate_id uuid,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  error text,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.qc_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  file_type text NOT NULL,
  bucket text NOT NULL,
  path text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.qc_points (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  param_code text,
  setpoint_nominal numeric,
  std_mean numeric,
  uut_mean numeric,
  correction_mean numeric,
  correction_stddev numeric,
  n_points integer,
  u95 numeric,
  unit text,
  meta jsonb,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.qc_uncertainty_components (
  id bigint NOT NULL DEFAULT nextval('public.qc_uncertainty_components_id_seq'::regclass),
  run_id uuid NOT NULL,
  param_code text,
  setpoint_nominal numeric,
  component text,
  value numeric,
  note text,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.qc_windows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  param_code text,
  setpoint_nominal numeric,
  start_ts timestamp with time zone,
  end_ts timestamp with time zone,
  direction text,
  notes text,
  PRIMARY KEY (id)
);

DO $bootstrap$
DECLARE
  missing text[];
BEGIN
  SELECT array_agg(t ORDER BY t)
  INTO missing
  FROM unnest(ARRAY[
    'calibration_import','calibration_import_mapping','calibration_import_sheet',
    'calibration_measurement','cmc_profiles','cmc_values','logger_discovery',
    'logger_rows','qc_files','qc_points','qc_runs','qc_uncertainty_components','qc_windows'
  ]) AS t
  WHERE to_regclass('public.' || t) IS NULL;

  IF missing IS NOT NULL THEN
    RAISE EXCEPTION 'Bootstrap gagal, tabel belum ada: %', array_to_string(missing, ', ');
  END IF;

  RAISE NOTICE 'Bootstrap staging selesai: seluruh tabel tambahan tersedia.';
END
$bootstrap$;
